apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f2piicr9a-go
  janus-idp.io/tekton: f2piicr9a-go
  backstage.io/kubernetes-id: f2piicr9a-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f2piicr9a-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
